// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `npx prisma dev` sobe PGlite, que so tem o banco template1: sem apontar o
    // shadow para a segunda instancia, o migrate usa o proprio banco de dev como
    // shadow e o replay das migracoes morre em "type Platform already exists".
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
